### ISSUE TITLE
random.choice() on a sentence generates a character

### ISSUE THREAD

**Issue by BiophysNinja** [Heidelberg-NLP/VALSE#3]
```
   for foil_id, foil in tqdm(foils_data.items()):
        caption_fits = foil['mturk']['caption']

        if caption_fits >= 2:  # valid examples only (validated by mturkers)

            test_img_path = os.path.join(images_path, foil["image_file"])

            if instrument == 'plurals':
                test_sentences = [foil["caption"][0], random.choice(foil["foils"])]
            else:
                test_sentences = [foil["caption"], random.choice(foil["foils"])]
```
why random.choice() used in here? that creates single character sentences

**Comment by BiophysNinja** [comment]
```
else:
    test_sentences = [foil["caption"], foil["foil"]]
```

"foils" needs to be changed to "foil" as well

**Comment by LetiP** [comment]
Thanks a lot for pointing this out to us! Just pushed a fix to this.

I forgot I had cleaned up the data format before publishing and tested this script on the uncleaned version, where you can guess, the `foil` entry was `foils` consisting of a list of one element (which in turn is a reminiscence from those times where we had more than one foil per data sample, therefore the random.choice).

In any case, this should be fixed now, thanks for your help and please let us know if you encounter any further problems. 🤝

**Comment by BiophysNinja** [comment]
Thank you for the quick response and the excellent work :).
