### ISSUE TITLE
No module named 'processing_image'

### ISSUE THREAD

**Issue by giobin** [Heidelberg-NLP/VALSE#5]
Hi,

very nice work and repo. I am trying it out, but as soon as I run 'lxmert_valse_eval.py' i get the error: 

`from processing_image import Preprocess`
`ModuleNotFoundError: No module named 'processing_image'`

which makes sense since there is no module 'processing_image' in the repo.
I think that this issue concerns also the imports of 'modeling_frcnn' and 'utils'.

Could you please update the repository with the 3 missing modules?

**Comment by LetiP** [comment]
Hi, thanks for noticing!
I just added the missing files in the latest commit e7e5e0111373dec2a2a7653caf27dc6dd351069c .
Just a thought: maybe since we conducted our work and wrote this code, there are simpler ways to run LXMERT from newer versions of huggingface.

**Comment by giobin** [comment]
Thank you. Now I confirm it works!
